version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - dupl
    - err113
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - misspell
    - modernize
    - nlreturn
    - nolintlint
    - perfsprint
    - revive
    - sqlclosecheck
    - testifylint
    - thelper
    - unparam
    - usestdlibvars
    - whitespace
    - wrapcheck
  settings:
    gocognit:
      min-complexity: 15
    gocritic:
      enabled-checks:
        - emptyStringTest
    gocyclo:
      min-complexity: 15
    nolintlint:
      require-explanation: true
      require-specific: true
    testifylint:
      enable-all: true
  exclusions:
    generated: strict
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
exclusions:
  rules:
    - path: _test\.go
      linters:
        - dupl
